### ISSUE TITLE
Please consider maintaining "official" KiCAD footprint and symbol libaries.

### ISSUE THREAD

**Issue by ghost** [tinypico/tinypico-hardware#1]
Those things are needlessly hard to search for by with too many projects. Your chance to be better!

For now, I made this. https://github.com/sonopard/tinypico-kicad-footprint

**Comment by UnexpectedMaker** [comment]
I don't use KiCAD so I won't be supplying footprints and design files, but I made the project open source so others can contribute too. So feel free to fork the project and submit pull requests for any KiCAD files you make and I can add them to the main repo.
