### ISSUE TITLE
Schematic for RGB IPS Display Shield 

### ISSUE THREAD

**Issue by patfelst** [tinypico/tinypico-hardware#11]
Hi Seon, is it possible to publish the schematic for your RGB IPS Display Shield please?

Thanks!

**Comment by mcauser** [comment]
Hi @patfelst I don't have the schematics, but I know the pinout:

|TinyPICO|IPS Display|
|-|-|
|n/c|MISO|
|GPIO23|MOSI|
|GPIO18|SCLK|
|GPIO5|CS|
|GPIO15|DC|
|GPIO14|Backlight|
|n/c|RST|
|3V3|VCC|
|GND|GND|

No MISO means you can only write data to the display, you can't read any data back.

**Comment by UnexpectedMaker** [comment]
Thanks for the push @patfelst ;)
https://github.com/tinypico/tinypico-hardware/tree/master/Shields/IPS%20Colour%20Display

**Comment by patfelst** [comment]
Thanks again
