### ISSUE TITLE
Honored but not sure if it was an accident.

### ISSUE THREAD

**Issue by Leviathan3DPrinting** [tinypico/tinypico-hardware#13]
I hopped on today to download the kicad symbol. I haven't tried it yet however, when going to download the files I noticed I had permission to edit the repo. I figured I would bring it to your attention as I wasn't sure if you did so on accident. I'm still waiting on my recent order to arrive but, I'm honored you'd trust me with permissions to your repo.

**Comment by nevercast** [comment]
Your user doesn't say contributor or maintainer. Are you sure you have writes to modify this repo and it's not GitHub abstracting away a fork of this repo ?
