### ISSUE TITLE
STL files

### ISSUE THREAD

**Issue by Death111** [tinypico/tinypico-hardware#14]
Hey,
I wanted to download TinyPICO_V2_USBC STL files https://github.com/tinypico/tinypico-hardware/tree/master/STL%20Files but only .step file is available. Do you also have STL files?

I want to use it as reference for 3d modeling case and to not have a tool supporting .step files.

Thanks
Death

**Comment by UnexpectedMaker** [comment]
Once I `finally` get the step modules finished, I'll see if I can export STL's as well.

**Comment by Death111** [comment]
I notice you were able to export the STL's :) Thanks @UnexpectedMaker 

~ https://github.com/tinypico/tinypico-hardware/tree/master/3D%20Files
