### ISSUE TITLE
tinypico board layout

### ISSUE THREAD

**Issue by bilaljo** [tinypico/tinypico-hardware#16]
I would like change out the prog resistor R3 against another (to change the battery current properly for my LiPo). Since I have only the schematic (and real board) it is hard to figure out which one is the correct one. I could only guess, which is quite unsafe.
Could you push an layout file of tiny pico (nano) as well?
Thanks.

**Comment by UnexpectedMaker** [comment]
Sorry, which board are you asking about the VBAT Prog resistor for? The TinyPICO or the TinyPICO Nano?

**Comment by bilaljo** [comment]
Sorry vergot to mention. The TinyPICO Nano.

**Comment by UnexpectedMaker** [comment]
I've highlighted the resistor with a blue outline.

![TinyPICO_Nano_Pinout_VBAT_Prog_Resistor](https://user-images.githubusercontent.com/3156212/123218404-0761ae80-d50f-11eb-9036-dea1be11acbc.jpg)

**Comment by bilaljo** [comment]
Great, that's what I was searching for! Thank you very much.

**Comment by UnexpectedMaker** [comment]
Nps!
