### ISSUE TITLE
Eagle and Gerbers do not match

### ISSUE THREAD

**Issue by fcapano** [tinypico/tinypico-hardware#2]
I've noticed some differences between the included gerber files and the Eagle project files.

For instance, the PSRAM' silkscreen is labeled "LY68L6400SLIT" in Eagle but simply "PSRAM" in the included gerbers.
Could you update the Eagle project so we are sure we're not missing any other more important change?

Thanks!

**Comment by UnexpectedMaker** [comment]
Files have been updated, cheers.
