### ISSUE TITLE
tinypico not upload program using platformio with micro USB

### ISSUE THREAD

**Issue by waqas-subhani** [tinypico/tinypico-hardware#26]
kindly help, if anyone of can. thanks

A fatal error occurred: Failed to connect to ESP32: Wrong boot mode detected (0x13)! The chip needs to be in download mode.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
*** [upload] Error 2

**Comment by UnexpectedMaker** [comment]
Sorry, not the place to ask this - It sounds like a platformIO configuration issue. Please try my discord server, or the platformIO community.
