### ISSUE TITLE
Comment GPS / GNSS / GSM / GPRS shield

### ISSUE THREAD

**Issue by Galaxy-Man** [tinypico/tinypico-hardware#27]
Great product and I can see a lot of uses for ESP32 in this size module. I am not a hardware designer, if I were I would do this myself. Are there are plans by anyone to make a GSM/GPRS/GPS/GNSS shiled of same form? I feel this would make the TinyPico more usable for a wider audience, Especially in field of IOT, tracking etc.

Thank you

**Comment by UnexpectedMaker** [comment]
I don't take requests like this...  sorry. 
Feel free to design one yourself, or contract someone to make one for you.
