### ISSUE TITLE
TinyPICO.sch and TinyPICO.brd

### ISSUE THREAD

**Issue by ghost** [tinypico/tinypico-hardware#28]
I can not open these two files with Engle. The error message I received is

line 9, column 122: This is not an EAGLE file.

I appreciate if someone can help me solve this issue.

Thanks,

Will

**Comment by UnexpectedMaker** [comment]
You haven't downloaded the files correctly from GitHub.
https://www.google.com/search?client=safari&rls=en&q=how+to+download+files+from+github&ie=UTF-8&oe=UTF-8

**Comment by ghost** [comment]
Thank you for your answer. I really appreciate it. Will
