### ISSUE TITLE
Add ov2460 camera

### ISSUE THREAD

**Issue by dontsovcmc** [tinypico/tinypico-hardware#6]
Thanks a lot for you tiny board! 
It's what I need. How do you think, is it hard to add ov2460 2MP camera module to the board? ESP32-CAM board is rather popular, but isn't power safety and big. I can help, if possible.

**Comment by UnexpectedMaker** [comment]
Feel free to make an OV2460 shield for the TinyPICO and contribute it back to the project, as it is open source after all.
