### ISSUE TITLE
Where can I download a 3D Model?

### ISSUE THREAD

**Issue by Pro** [tinypico/tinypico-hardware#7]
We would need the 3D Model of the TinyPico for building a Case and visualizing the board on it.

Could you add the model to the git repo (in the ideal case as STEP file)? Or is it available somewhere else?

**Comment by UnexpectedMaker** [comment]
Sorry, there is no 3D model for the TinyPICO.

Seon Rozenblum | Unexpected Maker
http://unexpectedmaker.com <http://unexpectedmaker.com/>

**Comment by Pro** [comment]
Bad news, but thanks anyways!

**Comment by taf2** [comment]
I found this one which is pretty good https://grabcad.com/library/tinypico-esp32-1  it is an older model but I've been using it with some success

[update] - the official one is perfect!

**Comment by UnexpectedMaker** [comment]
Official models are all available here.... :)
https://github.com/tinypico/tinypico-hardware/tree/master/3D%20Files
