### ISSUE TITLE
Low-Battery / Over discharge

### ISSUE THREAD

**Issue by CrispinPZA** [tinypico/tinypico-hardware#9]
What stops over discharge of the battery?

I can't see anything in the schematic that would handle this.

![image](https://user-images.githubusercontent.com/27884877/74865149-9aea0480-5348-11ea-9317-cc7597175368.png)
The ESP can operate down to 2.2V. With the LDO drop of 190mV that would pull the battery down to 2.3/2.4V before it would get flaky. A bit low for a li-ion battery.

Have I missed something?

**Comment by nevercast** [comment]
For what it's worth, the ESP32-PICO can only work down to 2.7V due to the internal flash being a 3v3 device. You will get flash errors lower than 2.7V

**Comment by UnexpectedMaker** [comment]
Yup, you need to use protected LiPos. The ones with the yellow on the top.
This really isn't a TinyPICO github issue, and is more a question for Discord :)

**Comment by CrispinPZA** [comment]
ah ok. Thanks.
So I'm not reading it wrong.

(Agreed on the last point 😄 )
